# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 11:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cms", "0005_https_logos")]

    operations = [
        migrations.AlterField(
            model_name="insightstag",
            name="tag",
            field=models.CharField(
                help_text=(
                    "Link to a tag on insights.ubuntu.com and pulls in"
                    " the RSS feed to the partner page."
                ),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="always_featured",
            field=models.BooleanField(
                default=False, help_text="Always promote to the top of lists."
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="dedicated_partner_page",
            field=models.BooleanField(
                help_text="Does this partner have it's own dedicated page?"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="fallback_website",
            field=models.URLField(
                help_text=(
                    "If our partner changes their site without us realising"
                    " it, and the 'external page' errors, this will be` used"
                    " instead."
                )
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="featured",
            field=models.BooleanField(help_text="Promote to the front page"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.URLField(
                help_text=(
                    "The URL to the logo (e.g. http://example.com/logo.svg)."
                    "\nPlease only upload .png and .svg files, no less than"
                    " 200 pixels wide.\n"
                )
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="long_description",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Only displayed on the dedicated partner page (when"
                    " 'generate page' is selected). (<a href='http://"
                    "daringfireball.net/projects/markdown/basics'>Markdown"
                    " formatted</a>)"
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Private, for internal Canonical use"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="partner_type",
            field=models.ManyToManyField(
                blank=True,
                help_text="test",
                null=True,
                related_name="partners",
                to="cms.PartnerType",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="partner_website",
            field=models.URLField(
                help_text=(
                    "The URL to the partner's site where the info about"
                    " partnering with Canonical is."
                )
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="published",
            field=models.BooleanField(
                help_text=(
                    "Partners without this checked will never be seen by the"
                    " public"
                )
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="short_description",
            field=models.TextField(
                help_text=(
                    "Used in search results, max 375 characters.(<a href="
                    "'http://daringfireball.net/projects/markdown/basics'>"
                    "Markdown formatted</a>)"
                ),
                validators=[django.core.validators.MaxLengthValidator(375)],
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="slug",
            field=models.SlugField(
                help_text="Auto-generated, for use in URLs", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="tags_label",
            field=models.CharField(
                blank=True,
                help_text="The displayed name for the tags list",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="text",
            name="html_class",
            field=models.CharField(
                blank=True,
                help_text=(
                    "The class added to the generated HTML for this" " section"
                ),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="A URL for an image to appear alongside the text",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="insights_tag",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Articles matching this insigts tag will be included"
                    " in the block. Leave blank for no insights feed."
                ),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="read_more_cta",
            field=models.BooleanField(
                default=False,
                help_text="Should the 'read more' link be a CTA button?",
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="read_more_external",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Does the 'read more' link to an external site (other"
                    " canonical sites or subdomains count as external)?"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="read_more_link_text",
            field=models.CharField(
                blank=True,
                help_text=(
                    "The content of the field's link. Leave blank for"
                    " 'read more'"
                ),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="A Youtube video URL.", null=True
            ),
        ),
    ]
